spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: demo_user
    password: demo_pass_123
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper XML ????
  type-aliases-package: com.example.demo.app.entity  # ????????? XML ??????
  configuration:
    map-underscore-to-camel-case: true  # ????????????? Java ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ?? SQL ??????

server:
  port: 8080
